spring:
  application:
    name: USER-API
  datasource:
    url: jdbc:mysql://localhost:3306/user-module
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  boot:
    admin:
      client:
        url: http://localhost:1111/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

#JWT CONFIG       

jwt:
 key: siuhdiashcaschasciuwyebhbchcdjhjacdjhca
 issuer: ankit
 expiry: 86400000
 
 
springdoc:
 api-docs:
  enabled: false 
 